#!/usr/bin/expect -f
# https://nicolasmontanaro.com/blog/9front-guide/

proc get_keepass { pass title type } {
   set channel [open "|kpcli --kdb beligos.kdbx -c \"show -f beligos/$title\" | grep \"$type:\" | cut -d: -f2 | cut -b2-" r+]
   puts $channel "$pass"
   flush $channel
   return [gets $channel]
}

puts "Enter new password for keepass(beligos.kdbx)\[echoed\]: "
gets stdin keepass_pass
set glenda_pass [get_keepass $keepass_pass "glenda" "Pass"]

set runner [lindex $argv 0]

set timeout -1
spawn $runner
expect "bootargs is *"
send "\r"
expect "user*:*"
send "\r"
expect "term% "
send "9fs 9fat; echo 'service=cpu' >>/n/9fat/plan9.ini\r"
expect "term% "
send "fshalt\r"
expect "term% "
send "2"
expect "(qemu)"
send "quit\r"
expect eof

spawn $runner
expect "bootargs is *"
send "\r"
expect "authid:*"
send "glenda\r"
expect "authdom:*"
send "localgrid\r"
expect "secstore key:*"
send "\r"
expect "password:*"
send "$glenda_pass\r"
expect "*# "
send "fshalt\r"
expect "*# "
send "2"
expect "(qemu)"
send "quit\r"
expect eof

spawn $runner
expect "bootargs is *"
send "local!/dev/sd00/fscache -c\r"
expect "config:*"
send "noauth\r"
expect "config:*"
send "noauth\r"
expect "config:*"
send "end\r"
expect "*# "
send "9fs 9fat; echo 'bootargs=local!/dev/sd00/fscache -a tcp!*!564' >>/n/9fat/plan9.ini\r"
expect "*# "
send "fshalt\r"
expect "*# "
send "2"
expect "(qemu)"
send "quit\r"
expect eof
