#!/usr/bin/expect -f
# https://nicolasmontanaro.com/blog/9front-guide/

proc get_keepass { pass title type } {
   set channel [open "|kpcli --kdb belagos.kdbx -c \"show -f belagos/$title\" | grep \"$type:\" | cut -d: -f2 | cut -b2-" r+]
   puts $channel "$pass"
   flush $channel
   return [gets $channel]
}

puts "Enter new password for keepass(belagos.kdbx)\[echoed\]: "
gets stdin keepass_pass
set glenda_pass [get_keepass $keepass_pass "glenda" "Pass"]

set img [lindex $argv 0]
set ram [lindex $argv 1]
set hostname [lindex $argv 2]
set mac [lindex $argv 3]
set mac2 [lindex $argv 4]

# Reset the hostname and MAC, then turn on CPU service
set timeout -1
spawn qemu-system-x86_64 -m $ram -net nic,model=virtio,macaddr=$mac -net user -device virtio-scsi-pci,id=scsi -drive if=none,id=vd0,file=$img -device scsi-hd,drive=vd0 -curses
expect "bootargs is *"
send "\r"
expect "user*:*"
send "\r"
expect "term% "
send "cat /lib/ndb/local | sed 's/sys=cirno/sys=$hostname/g' | sed 's/ether=52540000ee01/ether=$mac2/g' > /lib/ndb/local2; mv /lib/ndb/local2 /lib/ndb/local\r"
expect "term% "
send "9fs 9fat; echo 'service=cpu' >>/n/9fat/plan9.ini\r"
expect "term% "
send "fshalt\r"
expect "term% "
send "2"
expect "(qemu)"
send "quit\r"
expect eof


spawn qemu-system-x86_64 -m $ram -net nic,model=virtio,macaddr=$mac -net user -device virtio-scsi-pci,id=scsi -drive if=none,id=vd0,file=$img -device scsi-hd,drive=vd0 -curses
expect "bootargs is *"
send "\r"
expect "authid:*"
send "glenda\r"
expect "authdom:*"
send "localgrid\r"
expect "secstore key:*"
send "\r"
expect "password:*"
send "$glenda_pass\r"
expect "*# "
send "fshalt\r"
expect "*# "
send "2"
expect "(qemu)"
send "quit\r"
expect eof

# Turn on auth
spawn qemu-system-x86_64 -m $ram -net nic,model=virtio,macaddr=$mac -net user -device virtio-scsi-pci,id=scsi -drive if=none,id=vd0,file=$img -device scsi-hd,drive=vd0 -curses
expect "bootargs is *"
send "local!/dev/sd00/fscache -c\r"
expect "config:*"
send "noauth\r"
expect "config:*"
send "noauth\r"
expect "config:*"
send "end\r"
expect "*# "
send "9fs 9fat; echo 'bootargs=local!/dev/sd00/fscache -a tcp!*!564' >>/n/9fat/plan9.ini\r"
expect "*# "
send "fshalt\r"
expect "*# "
send "2"
expect "(qemu)"
send "quit\r"
expect eof
