#!/usr/bin/expect -f
# https://9p.io/wiki/plan9/Vmware_playground_for_plan9/index.html

proc get_keepass { pass title type } {
   set channel [open "|kpcli --kdb belagos.kdbx -c \"show -f belagos/$title\" | grep \"$type:\" | cut -d: -f2 | cut -b2-" r+]
   puts $channel "$pass"
   flush $channel
   return [gets $channel]
}

puts "Enter new password for keepass(belagos.kdbx)\[echoed\]: "
gets stdin keepass_pass
set glenda_pass [get_keepass $keepass_pass "glenda" "Pass"]

set img [lindex $argv 0]
set ram [lindex $argv 1]

set timeout -1
spawn qemu-system-x86_64 -m $ram -net nic,model=virtio,macaddr=52:54:00:00:EE:04 -net user -device virtio-scsi-pci,id=scsi -drive if=none,id=vd0,file=$img -device scsi-hd,drive=vd0 -boot n -curses
expect "bootargs is*"
sleep 2
send "\r"

# Partition our small disl
#disk/mbr /dev/sd00/data
#disk/fdisk /dev/sd00/data
#>>> a p0 0 1
#disk/prep /dev/sd00/plan9
#>>> a 9fat
#disk/fdisk -p /dev/sd00/data > /dev/sd00/ctl

#touch /dev/sd00/nvram
#echo 'nvram=/dev/sd00/nvram' >> /cfg/pxe/52540000ee04

expect "term% "

# Halt
send "fshalt\r"
expect "term% "
send "2"
expect "(qemu)"
send "quit\r"
expect eof
