#!/usr/bin/expect -f
# Installing 9front usually just pounding return unless there is "no default". Then you choose the first item. If you see ">>>", just type w\rq\r

set img [lindex $argv 0]
set ram [lindex $argv 1]
set iso [lindex $argv 2]
set size [lindex $argv 3]

set timeout -1

# Make base disk.
spawn qemu-img create -f qcow2 $img $size
expect eof

# Install base system. Use "-net user" so we can do this before rebooting
spawn qemu-system-x86_64 -m $ram -net nic,model=virtio,macaddr=52:54:00:00:EE:03 -net user -device virtio-scsi-pci,id=scsi -drive if=none,id=vd0,file=$img -device scsi-hd,drive=vd0 -drive if=none,id=vd1,file=$iso -device scsi-cd,drive=vd1,bootindex=0 -curses
expect "bootargs is *"
sleep 2
send "\r"
expect "user*:*"
send "\r"
expect "vgasize is (text, 640x480x8, 1024x768x16, ...)"
send "text\r"
expect "term% "
send "inst/start\r"
expect "Task to do *:*"
send "\r"
expect "File system *:*"
send "\r"
expect "Task to do *:*"
send "\r"
expect "Disk to partition *:*"
send "sd00\r"
expect "Install mbr or gpt *:*"
send "mbr\r"
expect ">>>"
send "w\rq\r"
expect "Task to do *:*"
send "\r"
expect "Plan 9 partition to subdivide *:*"
send "\r"
expect ">>>"
send "w\rq\r"
expect "Task to do *:*"
send "\r"
expect "Cwfs cache partition *:*"
send "\r"
expect "Cwfs worm partition *:*"
send "\r"
expect "Cwfs other partition *:*"
send "\r"
expect "Ream the filesystem? *:*"
send "\r"
expect "Task to do *:*"
send "\r"
expect "Distribution is from *:*"
send "\r"
expect "Task to do *:*"
send "\r"
expect "Configuration method *:*"
send "\r"
expect "Task to do *:*"
send "\r"
expect "Distribution disk *:*"
send "\r"
expect "Location of archives *:*"
send "\r"
expect "Task to do *:*"
send "\r"
expect "Task to do *:*"
send "\r"
expect "sysname *:*"
send "fsserve\r"
expect "Task to do *:*"
send "\r"
expect ", WET*:*"
send "US_Central\r"
expect "Task to do *:*"
send "\r"
expect "Plan 9 FAT partition *:*"
send "\r"
expect "Install the Plan 9 master boot record *:*"
send "yes\r"
expect "Mark the Plan 9 partition active *:*"
send "yes\r"
expect "Task to do *:*"
send "\r"
expect "Congratulations; you've completed the install."
send "2"
expect "(qemu)"
send "quit\r"
expect eof
