#!/usr/bin/expect -f
# https://9p.io/wiki/plan9/Vmware_playground_for_plan9/index.html

set glenda_pass ""
if {[info exists ::env(GLENDA_PASS)]} {
   set glenda_pass $::env(GLENDA_PASS)
}

set user_pass ""
if {[info exists ::env(USER_PASS)]} {
   set user_pass $::env(USER_PASS)
}

set runner [lindex $argv 0]

set timeout -1

# Create the nvram partition
spawn $runner -curses
expect "authid:"
send "glenda\r"
expect "authdom:"
send "localgrid\r"
expect "secstore key:"
send "$glenda_pass\r"
expect "password:"
send "$glenda_pass\r"
expect "Password:"
send "$glenda_pass\r"
expect "Confirm password:"
send "$glenda_pass\r"

# nvram
expect "# "
send "belagos_install/small_nvram.rc\r"

expect "# "
send "auth/wrkey\r"
expect "authid:"
send "glenda\r"
expect "authdom:"
send "localgrid\r"
expect "secstore key:"
send "$glenda_pass\r"
expect "password:"
send "$glenda_pass\r"
expect "# "
send "fshalt\r"
expect "# "
send "2"
expect "(qemu)"
send "quit\r"
expect eof

# Create Users
spawn $runner -curses
expect "# "
send "auth/changeuser glenda\r"
expect "Password:"
send "$glenda_pass\r"
expect "Confirm password:"
send "$glenda_pass\r"
expect "assign*POP*:"
send "n\r"
expect "Expiration*:"
send "\r"
expect "Post*:"
send "\r"
expect "*name:"
send "\r"
expect "Department*:"
send "\r"
expect "U*email address:"
send "\r"
expect "Spon*email address:"
send "\r"

if { $user_pass ne "" } {
   set user $::env(USER)
   expect "# "
   send "auth/changeuser $user\r"
   expect "Password:"
   send "$user_pass\r"
   expect "Confirm password:"
   send "$user_pass\r"
   expect "assign*POP*:"
   send "n\r"
   expect "Expiration*:"
   send "\r"
   expect "Post*:"
   send "\r"
   expect "*name:"
   send "\r"
   expect "Department*:"
   send "\r"
   expect "U*email address:"
   send "\r"
   expect "Spon*email address:"
   send "\r"
}

expect "# "
send "fshalt\r"
expect "# "
send "2"
expect "(qemu)"
send "quit\r"
expect eof
