#!/usr/bin/expect -f
# https://nicolasmontanaro.com/blog/9front-guide/

set glenda_pass ''
if {[info exists ::env(GLENDA_PASS)]} {
   set glenda_pass $::env(GLENDA_PASS)
}

set runner [lindex $argv 0]

# Turn on CPU Server
set timeout -1
spawn $runner -curses
expect "boot*\] "
send "\r"
expect "user*:*"
send "\r"
expect "term% "
send "9fs 9fat; echo 'service=cpu' >>/n/9fat/plan9.ini\r"
expect "term% "
send "fshalt\r"
expect "term% "
send "2"
expect "(qemu)"
send "quit\r"
expect eof

# Create user?
spawn $runner -curses
expect "boot*\] "
send "\r"
expect "authid:*"
send "glenda\r"
expect "authdom:*"
send "localgrid\r"
expect "secstore key:*"
send "$glenda_pass\r"
expect "password:*"
send "$glenda_pass\r"
expect "# "
send "fshalt\r"
expect "# "
send "2"
expect "(qemu)"
send "quit\r"
expect eof

# Turn on auth
spawn $runner -curses
expect "boot*\] "
send "local!/dev/sd00/fscache -c\r"
expect "config:*"
send "noauth\r"
expect "config:*"
send "noauth\r"
expect "config:*"
send "end\r"
expect "# "
send "9fs 9fat; echo 'nobootprompt=local!/dev/sd00/fscache -a tcp!*!564' >>/n/9fat/plan9.ini\r"
expect "# "
send "fshalt\r"
expect "# "
send "2"
expect "(qemu)"
send "quit\r"
expect eof

# Run final installer
spawn $runner -curses
expect "# "
send "mkdir belagos_install\r"
expect "# "
send "chmod 777 belagos_install\r"
expect "# "

# 9mount and copy scripts
exec mkdir fsserve_9fs
exec 9mount "tcp!192.168.9.3" fsserve_9fs
#exec cp rc/* fsserve_9fs/usr/glenda/belagos_install/
exec cp {*}[glob rc/*.rc] fsserve_9fs/usr/glenda/belagos_install/
exec 9umount fsserve_9fs
exec rmdir fsserve_9fs

send "chmod 700 belagos_install/\r"
expect "# "
send "belagos_install/fsserve_build.rc\r"
expect "# "
send "fshalt\r"
expect "# "
send "2"
expect "(qemu)"
send "quit\r"
expect eof

