#!/usr/bin/expect -f
# https://9p.io/wiki/plan9/Vmware_playground_for_plan9/index.html

set glenda_pass ''
if {[info exists ::env(GLENDA_PASS)]} {
   set glenda_pass $::env(GLENDA_PASS)
}

set runner [lindex $argv 0]

set timeout -1
spawn $runner -curses
expect "authid:"
send "glenda\r"
expect "authdom:"
send "localgrid\r"
expect "secstore key:"
send "$glenda_pass\r"
expect "password:"
send "$glenda_pass\r"

# nvram
expect "# "
send "disk/mbr /dev/sd00/data\r"
expect "# "
send "disk/fdisk -aw /dev/sd00/data\r"
expect "# "
send "disk/prep -a nvram -w /dev/sd00/plan9\r"
expect "# "
send "echo clear >/dev/sd00/nvram\r"
expect "# "
send "auth/wrkey\r"
expect "authid:"
send "glenda\r"
expect "authdom:"
send "localgrid\r"
expect "secstore key:"
send "$glenda_pass\r"
expect "password:"
send "$glenda_pass\r"
expect "# "
send "fshalt\r"
expect "# "
send "2"
expect "(qemu)"
send "quit\r"
expect eof
