#!/usr/bin/expect -f
# https://nicolasmontanaro.com/blog/9front-guide/

set glenda_pass 'changeme'
if {[info exists ::env(GLENDA_PASS)]} {
   set glenda_pass $::env(GLENDA_PASS)
}

set user_pass 'changeme'
if {[info exists ::env(USER_PASS)]} {
   set user_pass $::env(USER_PASS)
}

set runner [lindex $argv 0]

# Turn on CPU Server
set timeout -1
spawn $runner -curses
expect "boot*\] "
send "\r"
expect "user*:*"
send "\r"
expect "term% "
send "9fs 9fat; echo 'service=cpu' >>/n/9fat/plan9.ini\r"
expect "term% "
send "echo '*acpi=1' >>/n/9fat/plan9.ini\r"
expect "term% "
send "echo 'console=0' >>/n/9fat/plan9.ini\r"
expect "term% "
send "fshalt\r"
expect "term% "
send "2"
expect "(qemu)"
send "quit\r"
expect eof

# Create user?
spawn $runner -nographic
expect "boot*\] "
send "\r"
expect "authid:*"
send "glenda\r"
expect "authdom:*"
send "localgrid\r"
expect "secstore key:*"
send "$glenda_pass\r"
expect "password:*"
send "$glenda_pass\r"
expect "# "
send "fshalt\r"
expect eof

# Turn on auth
spawn $runner -nographic
expect "boot*\] "
send "local!/dev/sd00/fscache -c\r"
expect "config:*"
send "noauth\r"
expect "config:*"
send "noauth\r"
expect "config:*"
send "end\r"
expect "# "
send "9fs 9fat; echo 'nobootprompt=local!/dev/sd00/fscache -a tcp!*!564' >>/n/9fat/plan9.ini\r"
expect "# "
send "fshalt\r"
expect eof

# Run final installer
spawn $runner -nographic

if { $user_pass ne "" } {
   set user $::env(USER)
   expect "# "
   send "echo newuser $user >>/srv/cwfs.cmd\r"
}

expect "# "
send "mkdir belagos_install\r"
expect "# "
send "chmod 777 belagos_install\r"
expect "# "

# 9mount and copy scripts
catch {exec rmdir fsserve_9fs}
exec mkdir fsserve_9fs
exec 9mount "tcp!192.168.9.3" fsserve_9fs
exec cp {*}[glob rc/*.rc] fsserve_9fs/usr/glenda/belagos_install/
sleep 5
exec 9umount fsserve_9fs
exec rmdir fsserve_9fs

send "chmod 700 belagos_install/\r"
expect "# "
send "belagos_install/fsserve_build.rc\r"
expect "# "
#send "belagos_install/gui.rc\r"
#expect "# "
send "fshalt\r"
expect eof
