#!/usr/bin/expect -f
# https://nicolasmontanaro.com/blog/9front-guide/

set glenda_pass ''
if {[info exists ::env(PASS)]} {
   set glenda_pass $::env(PASS)
} else {
   puts "Enter password for glenda\[echoed\]: "
   gets stdin glenda_pass
}

set runner [lindex $argv 0]

# Turn on CPU Server
set timeout -1
spawn $runner -curses
expect "boot*\] "
send "\r"
expect "user*:*"
send "\r"
expect "term% "
send "9fs 9fat; echo 'service=cpu' >>/n/9fat/plan9.ini\r"
expect "term% "
send "fshalt\r"
expect "term% "
send "2"
expect "(qemu)"
send "quit\r"
expect eof

# Create user?
spawn $runner -curses
expect "boot*\] "
send "\r"
expect "authid:*"
send "glenda\r"
expect "authdom:*"
send "localgrid\r"
expect "secstore key:*"
send "$glenda_pass\r"
expect "password:*"
send "$glenda_pass\r"
expect "# "
send "fshalt\r"
expect "# "
send "2"
expect "(qemu)"
send "quit\r"
expect eof

# Turn on auth
spawn $runner -curses
expect "boot*\] "
send "local!/dev/sd00/fscache -c\r"
expect "config:*"
send "noauth\r"
expect "config:*"
send "noauth\r"
expect "config:*"
send "end\r"
expect "# "
send "9fs 9fat; echo 'nobootprompt=local!/dev/sd00/fscache -a tcp!*!564' >>/n/9fat/plan9.ini\r"
expect "# "

# Our network info and PXE
#send "echo 'auth=authserve.localgrid authdom=localgrid' >> /lib/ndb/local\r"
#expect "# "
#send "echo 'ipnet=localgrid ip=192.168.9.0 ipmask=255.255.255.0' >> /lib/ndb/local\r"
#expect "# "
#send "echo '    auth=authserve.localgrid' >> /lib/ndb/local\r"
#expect "# "
#send "echo '    dnsdom=localgrid' >> /lib/ndb/local\r"
#expect "# "
#send "echo '    cpu=cpuserve.localgrid' >> /lib/ndb/local\r"
#expect "# "
#send "echo '    fs=fsserve.localgrid' >> /lib/ndb/local\r"
#expect "# "
#send "mkdir /cfg/fsserve/\r"
#expect "# "
#send "mkdir /cfg/authserve/\r"
#expect "# "
#send "mkdir /cfg/cpuserve/\r"
#expect "# "
#send "echo 'echo ''add :: :: fdfc::1'' >/net/iproute' >> /cfg/fsserve/cpurc\r"
#expect "# "
#send "echo 'echo ''add :: :: fdfc::1'' >/net/iproute' >> /cfg/authserve/cpurc\r"
#expect "# "
#send "echo 'echo ''add :: :: fdfc::1'' >/net/iproute' >> /cfg/cpuserve/cpurc\r"
#expect "# "
#send "echo 'ip/tftpd' >> /cfg/fsserve/cpurc\r"
#expect "# "
#send "echo 'nobootprompt=tls' >> /cfg/pxe/default\r"
#expect "# "
#send "echo 'auth=authserve.localgrid' >> /cfg/pxe/default\r"
#expect "# "
#send "echo 'fs=fsserve.localgrid' >> /cfg/pxe/default\r"
#expect "# "
#send "echo 'vgasize=text' >> /cfg/pxe/default\r"
#expect "# "
#send "cat /cfg/plan9.ini | grep -v cdboot | grep -v '#' | grep -v 'vgasize' >> /cfg/pxe/default\r"
#expect "# "
#send "cp /cfg/pxe/default /cfg/pxe/52540000ee04\r"
#expect "# "
#send "echo 'service=cpu' >> /cfg/pxe/52540000ee04\r"
#expect "# "
#send "echo 'nvram=/dev/sd00/nvram' >> /cfg/pxe/52540000ee04\r"
#expect "# "
#send "cp /cfg/pxe/52540000ee04 /cfg/pxe/52540000ee05\r"
#expect "# "
#send "echo 'cpu=cpuserve.localgrid' >> /cfg/pxe/default\r"
#expect "# "
send "fshalt\r"
expect "# "
send "2"
expect "(qemu)"
send "quit\r"
expect eof
